using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Fams
{
    public partial class frmAllActs : Form
    {
        public frmAllActs()
        {
            InitializeComponent();

            System.Globalization.CultureInfo ci = new System.Globalization.CultureInfo("ka-GE");
            System.Threading.Thread.CurrentThread.CurrentCulture = ci;
            System.Threading.Thread.CurrentThread.CurrentUICulture = ci;

            // This line of code is generated by Data Source Configuration Wizard
            allActsTableAdapter.Fill(officeDataSet.AllActs);
        }

        private void printContextMenuItem_Click(object sender, EventArgs e)
        {
            gridControl.ShowPrintPreview();
        }
    }
}
