using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Globalization;
using System.Threading;
using DataBase;
using DevExpress.XtraGrid.Views.Grid;

namespace Fams
{
    public partial class frmMonitoring : Form
    {
        public frmMonitoring()
        {
            CultureInfo ci = new CultureInfo("ka-GE");
            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = ci;

            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            mn_MonitoringTableAdapter.Fill(officeDataSet.mn_Monitoring);
            mn_COMBO_MizaniTableAdapter.Fill(officeDataSet.mn_COMBO_Mizani);
            mn_ViolationTableAdapter.Fill(officeDataSet.mn_Violation);
        }

        private void monitoringView_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            GridView view = sender as GridView;
            view.FocusedColumn.View.CloseEditor();
            if (view.FocusedColumn.View.UpdateCurrentRow())
            {
                //Console.WriteLine("updated");
                mn_MonitoringTableAdapter.Update(officeDataSet.mn_Monitoring);
            }
        }

        private void violationView_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            GridView view = sender as GridView;
            view.FocusedColumn.View.CloseEditor();
            if (view.FocusedColumn.View.UpdateCurrentRow())
            {
                //Console.WriteLine("updated");
                mn_ViolationTableAdapter.Update(officeDataSet.mn_Violation);
            }
        }
    }
}
